mcu_quotes = {
    "Tony Stark": ["I am Iron Man.", "Genius, billionaire, playboy, philanthropist.", "And I... am Iron Man.", "Let's get some shawarma.", "There are no strings on me.", "Proof that a genius can bleed.", "Part of the journey is the end.", "Big man in a suit of armor. Take that off, what are you?", "Alright, let's go get some shawarma.", "Sometimes you gotta pull yourself up by your bootstraps.", "And as far as the future is concerned, I'm working on it.", "Peace in our time? It doesn't work.", "My armor, it was never a distraction or a hobby. It was a cocoon. And now, I'm a changed man.", "You can take away my house, all my tricks and toys. One thing you can't take away? I am Iron Man.", "I love you 3000."],
    "Uncle Ben": ["With great power comes great responsibility."],
    "Captain America": ["Avengers Assemble!", "I can do this all day.", "Maybe I was wrong about you. Maybe there is still good in you.", "Avenge the fallen.", "On your left!", "I never thought I'd die fighting side by side with an alien.", "Here goes nothing.", "There should be more to life than this."],
    "Doctor Strange": ["Dormammu, I've come to bargain."],
    "T'Challa": ["Wakanda Forever!", "Let me tell you something. I am not afraid."],
    "Vision": ["A thing isn't beautiful because it lasts. It's beautiful because it existed.", "What is grief, if not love persevering?"],
    "Steve Rogers": ["No. I am Steve Rogers.", "You're not wrong. You're just an asshole.", "We fight for what we believe in, even if we're the only ones left.", "Get this man a shield!", "Whatever it takes.", "I used to want you dead.", "This is for you, Peggy."],
    "Yondu": ["He may have been your father, but he wasn't your daddy.", "I'm Mary Poppins, y'all!"],
    "The Ancient One": ["Whoever controls the past controls the future. Whoever controls the present controls the past."],
    "Thanos": ["The hardest choices require the strongest wills.", "I am inevitable.", "Is this not your victory, Loki? The world is in chaos. Kneel!", "Is that the best you can do?"],
    "Gamora": ["Everything beautiful is fleeting.", "Sometimes you gotta run before you can walk.", "There's no 'we' here."],
    "Bruce Banner": ["I'm always angry."],
    "Nick Fury": ["There's no shame in who you are.", "Get used to feeling like crap, kid. Because it comes with the territory.", "I'm here to talk about the Avengers Initiative.", "If you can't protect the planet, you can't protect the universe."],
    "Groot": ["We are Groot.", "We are Groot. (final words)", "I am... Groot."],
    "Peggy Carter": ["A hero doesn't need to be able to fly to save the day."],
    "Thor": ["For Asgard!", "I choose to run towards my problems, not away from them.", "He's adopted."],
    "Sam Wilson": ["Some people move on. But not us.", "On your left!"],
    "Ho Yinsen": ["Don't waste it. Don't waste your life."],
    "Aunt May": ["You get hurt, you heal. You fall, you get up. You keep moving forward."],
    "James Rhodes": ["Even for a billionaire, that's a bit greedy."],
    "Star-Lord": ["Next time baby!", "Before we get started, does anyone want to get out?"],
    "Carol Danvers": ["And sometimes, the best revenge is living well."],
    "Loki": ["So long, suckers!", "Is it too late to apologize?"],
    "Peter Parker": ["Hi, I'm Peter Parker.", "I don't feel so good, Mr. Stark.", "With great power, there must also come great responsibility."],
    "Red Skull": ["The future doesn't belong to those who are content with today."],
    "Iron Man": ["But how about fighting alongside a friend?", "He may be a god, but he bleeds."],
    "Bucky Barnes": ["A man has no right to bring ruin upon others.", "Even if it means giving up everything.", "I used to want you back."],
    "Rocket": ["There's a star-lord out there who needs a little saving.", "No offense, but are you sure you're up for this?", "A thief? I'm a treasure hunter!"],
    "Killmonger": ["We're not so different, you and I.", "Wakanda doesn't do outreach."],
    "Black Panther": ["Yes, we are."],
    "Justin Hammer": ["If you're nothing without the suit, then you shouldn't have it."],
    "Dolphin": ["So long, farewell, and thanks for all the fish!"],
    "Stan Lee": ["Excelsior!"],
    "Venom": ["We are Venom."],
    "Okoye": ["The world may end, but we'll fight like hell first."],
    "Black Widow": ["On second thought, let's not go to Camelot. It's a silly place.", "He may be a god, but he bleeds."],
    "Scarlet Witch": ["We are stronger together."],
    "Hawkeye": ["I'm not a hero. I never wanted to be one. I just do what's right."],
    "John Walker": ["You know me?"],
    "Iron Man (repeated)": ["Part of the journey is the end.", "Big man in a suit of armor. Take that off, what are you?"]
}